Insert scripts for LR/Ferry

UPDATE "ABP_MAIN"."LOCALE" set description = 'Central LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '801';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Capitol Square LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '802';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Paddys Markets LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '803';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Exhibition Centre LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '804';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Convention LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '805';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Pyrmont Bay LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '806';
UPDATE "ABP_MAIN"."LOCALE" set description = 'The Star LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '807';
UPDATE "ABP_MAIN"."LOCALE" set description = 'John Street Square LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '808';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Fish Market LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '809';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Wentworth Park LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '810';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Glebe LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '811';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Jubilee Park LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '812';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Rozelle Bay LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '813';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Lilyfield LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '814';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Leichhardt North LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '815';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Hawthorne LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '816';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Marion LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '817';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Taverners Hill LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '818';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Lewisham West LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '819';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Waratah Mills LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '820';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Arlington LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '821';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Dulwich Grove LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '822';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Dulwich Hill LR', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '823';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Circular Quay, No. 2 Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '935';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Circular Quay, No. 3 Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '936';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Circular Quay, No. 4 Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '937';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Circular Quay, No. 5 Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '938';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Manly Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '939';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Garden Island Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '943';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Cockatoo Island Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '944';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Darling Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '945';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Double Bay Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '946';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Rose Bay Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '947';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Watsons Bay Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '948';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Pyrmont Bay Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '950';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Birchgrove Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '952';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Balmain Ferry Wharf Thames St', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '953';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Balmain East Darling St Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '954';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Abbotsford Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '955';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Chiswick Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '956';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Drummoyne Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '957';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Huntleys Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '958';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Barangaroo, Wharf 1', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '959';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Barangaroo, Wharf 2', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '960';
UPDATE "ABP_MAIN"."LOCALE" set description = 'McMahons Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '961';
UPDATE "ABP_MAIN"."LOCALE" set description = 'North Sydney Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '962';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Milsons Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '963';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Kirribilli Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '964';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Greenwich Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '965';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Mosman Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '968';
UPDATE "ABP_MAIN"."LOCALE" set description = 'South Mosman Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '969';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Taronga Zoo Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '970';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Neutral Bay Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '971';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Kurraba Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '972';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Cremorne Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '973';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Old Cremorne Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '974';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Woolwich Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '977';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Kissing Point Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '979';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Meadowbank Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '980';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Rydalmere Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '981';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Olympic Park Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '982';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Cabarita Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '983';
UPDATE "ABP_MAIN"."LOCALE" set description = 'Parramatta Ferry Wharf', inserted_dtm = sys_extract_utc(systimestamp) where locale_id = '985';
