desc EMV.MERCHANT_TXN_PENDING;
select * from EMV.MERCHANT_TXN_PENDING mtp
where mtp.RETRIEVALREFNO = '000062604135'
;

select * from EMV.TRANSIT_ACCOUNT_X_TOKEN tat where tat.TRANSITACCOUNTID = 100015514413;
select * from ABP_MAIN.TRANSIT_ACCOUNT_X_TOKEN tat where tat.TRANSIT_ACCOUNT_ID = '100015514829';

define l_testTransitAccountID = 100015555244;
define l_rrn = '000062603936';
define l_timezoneModifier = 10;
define TestDate = TO_DATE('31/JUL/2019 00:00:00', 'DD/MM/YYYY HH24:MI:SS');

select je.JOURNALENTRYID, je.TRANSITACCOUNTID, je.BANKCARDPAYMENTID, je.TRIPID, je.TRANSACTIONDTM + &l_timezoneModifier/24 as JE_DTM,
tr.ENTRYTRANSACTIONDTM + &l_timezoneModifier/24 as ENTRY_TAP_DTM, tr.EXITTRANSACTIONDTM + &l_timezoneModifier/24 as EXIT_TAP_DTM, tr.TOKENID,
bp.PGRETRIEVALREFNBR as RRN,
tr.FAREDUE as TRIP_FAREDUE, 
je.TRANSACTIONAMT as JE_TXN_AMT, 
bp.PGSETTLEMENTAMT as ABP_SETT_AMT, 
cf.I004AMOUNTTRANSACTION as CPA_AMT, 
je.EMVINSERTEDDTM,  bp.PGSETTLEMENTDTM, bp.PGRESPONSECODE, bp.INSERTEDDTM + &l_timezoneModifier/24,
cf.MSGDTM, cf.MSGSETTLEMENTSTATUS, cf.INSERTEDDTM, cf.UPDATEDDTM
from emv.journal_entry je
full outer join EMV.BANKCARD_PAYMENT bp on je.BANKCARDPAYMENTID = bp.BANKCARDPAYMENTID
join EMV.CONFIRMATION cf on bp.PGRETRIEVALREFNBR = cf.I037RETRIEVALREFERENCENUM 
left join EMV.TRIP tr on tr.TRIPID = je.TRIPID
where je.TRANSITACCOUNTID = '100015514944'
order by je.TRANSACTIONDTM desc
;


select je.JOURNALENTRYID, je.TRANSITACCOUNTID, tr.TOKENID, je.BANKCARDPAYMENTID, je.TRIPID, je.TRANSACTIONDTM + &l_timezoneModifier/24 as JE_DTM,
tr.ENTRYTRANSACTIONDTM + &l_timezoneModifier/24 as ENTRY_TAP_DTM, tr.EXITTRANSACTIONDTM + &l_timezoneModifier/24 as EXIT_TAP_DTM, 
bp.PGRETRIEVALREFNBR as RRN,
tr.FAREDUE as TRIP_FAREDUE, 
je.TRANSACTIONAMT as JE_TXN_AMT, 
bp.PGSETTLEMENTAMT as ABP_SETT_AMT, 
cf.I004AMOUNTTRANSACTION as CPA_AMT, 
je.EMVINSERTEDDTM,  bp.PGSETTLEMENTDTM, bp.PGRESPONSECODE, bp.INSERTEDDTM + &l_timezoneModifier/24,
cf.MSGDTM, cf.MSGSETTLEMENTSTATUS, cf.INSERTEDDTM, cf.UPDATEDDTM
from emv.journal_entry je
full outer join EMV.BANKCARD_PAYMENT bp on je.BANKCARDPAYMENTID = bp.BANKCARDPAYMENTID
join EMV.CONFIRMATION cf on bp.PGRETRIEVALREFNBR = cf.I037RETRIEVALREFERENCENUM 
left join EMV.TRIP tr on tr.TRIPID = je.TRIPID
where 
cf.I037RETRIEVALREFERENCENUM  = '000062604067'
order by je.TRANSACTIONDTM desc
;

select * from emv.trip tr
where tripid between 8594342 and 8594342;

select * from abp_main.trip
where trip_id between 8594500 and 8594700;

select * from EMV.CTP_REPORTS;




SELECT /*+ index(TAP IN1_TAP)*/ sys_extract_utc(systimestamp) - INSERTED_DTM AS DEPTH,
                                tap.TAP_ID, tap.TRANSACTION_DTM + 10/24, tap.TOKEN_ID, tap.TRANSIT_ACCOUNT_ID
FROM abp_main.tap
WHERE UNMATCHED_FLAG = '2'
ORDER BY sys_extract_utc(systimestamp) - INSERTED_DTM DESC;

select * from ABP_MAIN.WORK_X_TOKEN where WORK_ID = '888888888888888888';