insert ALL
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('825', 'Circular Quay LR', 825, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('826', 'Bridge Street LR', 826, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('827', 'Wynyard LR', 827, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('828', 'QVB LR', 828, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('829', 'Town Hall LR', 829, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('830', 'Chinatown LR', 830, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('831', 'Haymarket LR', 831, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('832', 'Central Chalmers Street LR', 832, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('833', 'Surry Hills LR', 833, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('834', 'Moore Park LR', 834, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('835', 'ES Marks LR', 835, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('836', 'Kensington LR', 836, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('837', 'UNSW Anzac Parade LR', 837, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('838', 'Kingsford LR', 838, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('839', 'Juniors Kingsford LR', 839, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('840', 'Royal Randwick LR', 840, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
--INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
--HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
--VALUES
--('841', 'Wansey Road LR', 841, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
--TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('842', 'UNSW High Street LR', 842, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
INTO abp_main.locale (LOCALE_ID, DESCRIPTION, SYSTEM_ID, LOCALE_TYPE_ID, NEXT_XFER_FREE_FLAG, TAP_MODE_OVERRIDE_ID, HOLD_AMT,
HOLD_AMT_OVERRIDE_FLAG, INSERTED_DTM, UPDATED_DTM, DOWNTOWN_FLAG)
VALUES
('843', 'Randwick LR', 843, 3, 0, 0, 0, 0,  TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') ,  
TO_TIMESTAMP((TO_CHAR(sysdate - 10/24,'DD-MM-YYYY HH24:MI:SS')), 'DD-MM-YYYY HH24:MI:SS') , 0)
SELECT * from DUAL
;

select * from abp_main.locale where system_id between 825 and 845 order by locale_id asc;

/* run below after loading
*/
-- Both Views must be refreshed
--BEGIN DBMS_SNAPSHOT.REFRESH( '"ABP_MAIN"."FARE_RULE_IN_USE"'); end;
--BEGIN DBMS_SNAPSHOT.REFRESH( '"ABP_MAIN"."FARE_RULE_X_CONC_LEVEL_IN_USE"'); end;

select * from abp_main.fare_rule_in_use
where ENTRY_LOCALE_ID = '825';

update ABP_MAIN.SYS_INFO
set MAX_FARE_RULE_EFFECTIVE_DTM  = TO_TIMESTAMP('2019-08-19 15:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF6') -10/24
;
